---
- 
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts: localhost
  vars_prompt:
  - name: email
    prompt: What is your email for github and ssh key?
    private: false

  tasks:
    - name: Install 1Password
      community.general.homebrew_cask:
        name: 1password
        state: present

    - name: Install VSCode
      community.general.homebrew_cask:
        name: visual-studio-code
        state: present

    # TODO: Make optional https://stackoverflow.com/a/48781996
    # - name: Install Google Chrome
    #   community.general.homebrew_cask:
    #     name: google-chrome
    #     state: present

    - name: Install Spotify
      community.general.homebrew_cask:
        name: spotify
        state: present

    - name: Install Iterm2
      community.general.homebrew_cask:
        name: iterm2
        state: present

    - name: Install Slack
      community.general.homebrew_cask:
        name: slack
        state: present

    # TODO: Make optional https://stackoverflow.com/a/48781996
    # - name: Install Steam
    #   community.general.homebrew_cask:
    #     name: steam
    #     state: present

    - name: Install Better Touch Tool
      community.general.homebrew_cask:
        name: bettertouchtool
        state: present

    - name: Install Authy
      community.general.homebrew_cask:
        name: authy
        state: present

    - name: Install Sublime Merge
      community.general.homebrew_cask:
        name: sublime-merge
        state: present

    - name: Install VLC
      community.general.homebrew_cask:
        name: vlc
        state: present

    - name: Install direnv
      community.general.homebrew:
        name: direnv
        state: present

    # Profile
    - name: history customizations
      blockinfile:
        path: ~/.zshrc
        create: yes
        marker: "# {mark} history fixes fix #"
        block: |
          setopt HIST_EXPIRE_DUPS_FIRST
          setopt HIST_IGNORE_DUPS
          setopt HIST_IGNORE_ALL_DUPS
          setopt HIST_IGNORE_SPACE
          setopt HIST_FIND_NO_DUPS
          setopt HIST_SAVE_NO_DUPS

    - name: WORDCHARS fix
      blockinfile:
        path: ~/.zshrc
        create: yes
        marker: "# {mark} WORDCHARS fix #"
        block: |
          export WORDCHARS="*?_-[]~=;!$%^(){}<>"

    # Files
    - name: Project Symlink
      ansible.builtin.file:
        src: ~/Library/Mobile Documents/com~apple~CloudDocs/Projects/
        dest: ~/Projects
        state: link

    # Dock
    - name: Copy file Dock plist file
      ansible.builtin.copy:
        src: '{{playbook_dir}}/configs/com.apple.dock.plist'
        dest: ~/Library/Preferences/com.apple.dock.plist
    - name: Restart Dock
      ansible.builtin.command: killall Dock

    # # TODO: Make optional https://stackoverflow.com/a/48781996
    # Steam
    # - name: Install Rosetta
    #   ansible.builtin.command: softwareupdate --install-rosetta --agree-to-license

    # Git
    - name: git Name
      ansible.builtin.command: git config --global user.name "Kamyar Ghasemlou"
    - name: git Email
      ansible.builtin.command: git config --global user.email {{ email }}
    # SSH key setup
    - name: .ssh exists
      file:
        path: ~/.ssh
        state: directory
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: ~/.ssh/github
        comment: "{{ email }}"
        size: 4096
    - name: SSH config
      blockinfile:
        path: ~/.ssh/config
        create: yes
        marker: "# {mark} ssh config #"
        block: |
          Host *
          AddKeysToAgent yes
          UseKeychain yes
          IdentityFile ~/.ssh/id_rsa
    - name: Add SSH key and copy the public one
      ansible.builtin.command: eval $(ssh-agent -s) && ssh-add --apple-use-keychain ~/.ssh/github && pbcopy < ~/.ssh/github.pub 
    - name: Add SSH key and copy the public one
      ansible.builtin.command: open https://github.com/settings/ssh/new

    # Finish
    - debug:
        msg: Done!
# btt
# iterm2
# backup
# zoom
# dock
# separate desktops
